### ISSUE TITLE
`ACCESS-OM3` Deployment on Gadi Killed during `esmf` `build` Phase

### ISSUE THREAD

**Issue by CodeGat** [ACCESS-NRI/ACCESS-OM3#8]
Pull request in question: https://github.com/ACCESS-NRI/ACCESS-OM3/pull/5

Within the above pull request, during the deployment of `ACCESS-OM3`, our jobs seemingly get killed by Gadi during `esmf`s `build` phase. Examples of these runs are at the bottom of the PR: 
* https://github.com/ACCESS-NRI/ACCESS-OM3/actions/runs/8793833929/job/24135789008
* https://github.com/ACCESS-NRI/ACCESS-OM3/actions/runs/8793833929/job/24133442178
* https://github.com/ACCESS-NRI/ACCESS-OM3/actions/runs/8793833929/job/24132330321

It may be something to do with an Out Of Memory Error being triggered by Gadi during that phase.

**Potential Solutions**
* Find a way to parallelize `esmf` build phase?

Pinging @micaeljtoliveira - have you had any experience with an issue like this when building `ACCESS-OM3` on Gadi?

**Comment by micaeljtoliveira** [comment]
@CodeGat Where is the compilation happening? On a login or a compute node?


> Find a way to parallelize esmf build phase?

By default spack does parallelize builds. What it does not by default is to parallelize over builds, but that's a bit more tricky and not relevant here.

**Comment by CodeGat** [comment]
The compilation is happening on a login node

**Comment by micaeljtoliveira** [comment]
There are several limits enforced on the login nodes regarding memory usage and CPU time. I strongly recommend you move the builds to a compute node. That will require submitting a job though...

**Comment by aidanheerdegen** [comment]
> That will require submitting a job though...

And attendant wait in the queue for every build job. Would really like to avoid that if possible.

**Comment by CodeGat** [comment]
Have confirmed that, for install of `access-om3` with `spack -d install --fresh` on `Gadi`:
* `--jobs 8` fails on `esmf` build stage
* `--jobs 4` succeeds
Will need to test how long it takes to install something like `om2` with `--jobs 4` vs not specifying `--jobs`.

**Comment by CodeGat** [comment]
Just to finish up on this conversation thread, it's now a per-model `vars.SPACK_INSTALL_PARALLEL_JOBS` rather than an explicit, global `--jobs 4`.
