### ISSUE TITLE
ESMF needs `-fp-model=precise`

### ISSUE THREAD

**Issue by anton-seaice** [ACCESS-NRI/ACCESS-OM3#9]
Per https://github.com/COSIMA/access-om3/issues/40#issuecomment-1641123313 the ESMF dependency needs to be built with `-fp-model=precise` to ensure BFB reproducibility.

In the COSIMA spack we had ESMF+debug set, which may have included this flag.

We don't want to always build with debug and +debug has been removed in the [config under test](https://github.com/ACCESS-NRI/ACCESS-OM3/blob/f48963a92c6799aaa0a5131c7f070fc373bea861/spack.yaml#L15). We need to set `-fp-model=precise` separately for production build. Is this only an option for intel-compilers?

I think we need to update the ESMF package definition to include the fp-model=precise flag?

I am not totally on top of the details, we might need @micaeljtoliveira 's input to be sure of the details.

Ping @CodeGat

**Comment by CodeGat** [comment]
This might also need @harshula s eyes. Will look into it.

**Comment by harshula** [comment]
Hi @micaeljtoliveira , 

The `access-om3-nuopc` SPD currently has: `depends_on("parallelio fflags='-qno-opt-dynamic-align -convert big_endian -assume byterecl -ftz -traceback -assume realloc_lhs -fp-model source' cflags='-qno-opt-dynamic-align -fp-model precise -std=gnu99'")`. i.e. `fflags` with `fp-model` set to `source` and `cflags` with  `fp-model` set to `precise`.

Do you want `depends_on("esmf@8.3.0:")` to include `cflags='-fp-model precise'` and `fflags='-fp-model precise'` ?

**Comment by micaeljtoliveira** [comment]
> In the COSIMA spack we had ESMF+debug set, which may have included this flag.

The debug variant will add the `-debug` and `-g` compiler flags, which, by default, will disable optimizations (one has to explicitly add  the optimization flags to prevent this)). So in practice, as a side-effect,  it does makes the build bit-wise reproducible.


> Do  you want depends_on("esmf@8.3.0:") to include cflags='-fp-model precise' and fflags='-fp-model precise' ?

If you want to enforce bit-wise reproducibility, yes.

**Comment by harshula** [comment]
Hi @anton-seaice , Can you please test the `spack-packages` `development` branch? It contains: https://github.com/ACCESS-NRI/spack-packages/compare/main...development
